<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>0dd3ff35-bac8-430e-98e9-7ae6c7ddf9fa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusTracker.Application\BusTracker.Application.csproj" />
    <ProjectReference Include="..\BusTracker.Infrastructure\BusTracker.Infrastructure.csproj" />
  </ItemGroup>

</Project>
